function [fillTime,maxTempToOptimize, ceq] = ExcelProfile(inputFiles,...
    PressureDataFile, TempDataFile, blnOneZone, blnThrottling, ...
    blnConstMassFlow, constMassFlow, OutputFolder, OutputPrefix, ...
    refpropdir)


% Read inlet profile for pressure and temperature from .xlsx files
InletPressureData = xlsread(PressureDataFile);
InletTempData = xlsread(TempDataFile);

if nargin < 5
  [fillTime,maxTempToOptimize, ceq] = MainRoutine(inputFiles,...
    InletPressureData, InletTempData, blnOneZone)
else
[fillTime,maxTempToOptimize, ceq] = MainRoutine(inputFiles,...
    InletPressureData, InletTempData, blnOneZone, ConstTempK, ...
    ConstPressKPa, blnThrottling, blnConstMassFlow, constMassFlow, ...
    OutputFolder, OutputPrefix, refpropdir)
end